## 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating tenors

PyTorch tensors are created using `torch.tensor()`

In [ ]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

### Function of `.ndim` is to tell the user that a scalar has no dimensions

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

### `.shape` tells us the shape

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

### A Square bracket means a dimension

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

Why Random Tensors?

Random tensors are important because the way many neural networks learn is that the start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random number -> look at data -> update random number -> look at data -> update random number`

In [ ]:
# Creating a random tensor with pytorch of size(3, 4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7104, 0.6990, 0.0349, 0.5620],
        [0.8193, 0.8388, 0.9912, 0.3711],
        [0.8627, 0.3320, 0.5222, 0.1166]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Creating a tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [ ]:
#Create a tensor of all zeroes

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor pf all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Using torch.range()

torch.range(0,10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten=torch.arange(0,10)

In [ ]:
one_to_ten=torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating Tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #Datatype
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

### You get an error if you play with tensors on different devices

### `requires_grad` tells pytorch to track gradients

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10

tensor * 10


tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Substract 10

tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch's inbuilt function

torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two ways of Multiplication in neural networks and deep learning :

1. Element Wise Multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
# Element wise Multiplication

print(tensor, "*", tensor)
print(f"Equals : {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 4.54 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 77 µs, sys: 0 ns, total: 77 µs
Wall time: 82 µs


tensor(14)

### One of the most common erorrs in deep learning : shape errors



In [ ]:
# Shapes for matrix multiplications

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) 

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our ternsors using a **transpose**

A **transpose** switches axes or dimensions of a given tensor

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Finding the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Finding the mean
#`torch.mean()` requires a float32 data type to work

torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
#Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding positional min and max

In [ ]:
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape 
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - Combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Adds all `1` dimensions to a tensor
* Permute - Return a view of the inpiut with dimensions permuted (swapped) in a certain way


In [ ]:
# Creating a tensor
import torch
x = torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
#add an extra dimension

x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [ ]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]), torch.Size([5, 2]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]), torch.Size([9, 1]))

In [ ]:
#Change the view


RuntimeError: ignored

##Pytorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

And because of thi, Pytorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor

import torch
import numpy as ndim

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproducibility (trying to take random out of a random)'

In short how a neural network learns :

` start with random numbers -> tensor 
operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
torch.rand(3, 3)

tensor([[0.6959, 0.5972, 0.6436],
        [0.8107, 0.9613, 0.2849],
        [0.7928, 0.7579, 0.1029]])

In [ ]:
import torch

#create two random tensors

random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[8.5741e-02, 5.3111e-01, 1.9772e-01, 8.9936e-01],
        [3.6168e-04, 2.8726e-01, 4.9515e-01, 1.0837e-02],
        [9.7575e-01, 7.7695e-01, 6.9212e-01, 8.0229e-01]])
tensor([[0.0949, 0.9143, 0.5248, 0.0268],
        [0.9090, 0.4009, 0.3804, 0.5416],
        [0.7878, 0.4490, 0.3505, 0.9743]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)


1. Get a gpu from google colab
2. Use your own - takes a bit of setup, requires investment
3. Use cloud computing - GCP, AWS, Azure

In [ ]:
!nvidia-smi

Fri Oct 28 05:59:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    12W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
#Setup Device Agnostic Code

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices

torch.cuda.device_count()

1